#ifdef TEXTURE_SLOT
TEXTURE_SLOT(REGISTER_0)
TEXTURE_SLOT(REGISTER_1)
TEXTURE_SLOT(REGISTER_2)
TEXTURE_SLOT(REGISTER_3)
TEXTURE_SLOT(REGISTER_4)
TEXTURE_SLOT(REGISTER_5)
TEXTURE_SLOT(REGISTER_6)
TEXTURE_SLOT(REGISTER_7)
TEXTURE_SLOT(REGISTER_8)
TEXTURE_SLOT(REGISTER_9)
TEXTURE_SLOT(REGISTER_10)
TEXTURE_SLOT(REGISTER_11)
TEXTURE_SLOT(REGISTER_12)

TEXTURE_SLOT_ALT(DIFFUSE) = REGISTER_0,
TEXTURE_SLOT_ALT(ALBEDO) = REGISTER_0,
TEXTURE_SLOT_ALT(REFRACTION) = REGISTER_0,

TEXTURE_SLOT_ALT(NORMAL) = REGISTER_1,
TEXTURE_SLOT_ALT(LUMINANCE) = REGISTER_1,

TEXTURE_SLOT_ALT(ROUGHNESS) = REGISTER_2,
TEXTURE_SLOT_ALT(AVG_LUMINANCE) = REGISTER_2,

TEXTURE_SLOT_ALT(METALNESS) = REGISTER_3,
TEXTURE_SLOT_ALT(REFLECTION) = REGISTER_3,
TEXTURE_SLOT_ALT(LUMINANCE_COPY) = REGISTER_3,

TEXTURE_SLOT_ALT(EMISSIVE) = REGISTER_4,

TEXTURE_SLOT_ALT(OPACITY) = REGISTER_5,
TEXTURE_SLOT_ALT(PARTICLES) = REGISTER_5,

TEXTURE_SLOT_ALT(AO) = REGISTER_6,

TEXTURE_SLOT_ALT(DEPTH) = REGISTER_7,

TEXTURE_SLOT_ALT(SHADOWMAP) = REGISTER_8,

TEXTURE_SLOT_ALT(CUBEMAP) = REGISTER_9,

TEXTURE_SLOT_ALT(SSAO) = REGISTER_10,

TEXTURE_SLOT_ALT(DUDV) = REGISTER_11,
TEXTURE_SLOT_ALT(SSR) = REGISTER_12,
#else


TEXTURE_SLOT_ALT(DIFFUSE)
TEXTURE_SLOT_ALT(ALBEDO)
TEXTURE_SLOT_ALT(REFRACTION)
TEXTURE_SLOT_ALT(NORMAL) 
TEXTURE_SLOT_ALT(LUMINANCE) 
TEXTURE_SLOT_ALT(ROUGHNESS) 
TEXTURE_SLOT_ALT(AVG_LUMINANCE) 
TEXTURE_SLOT_ALT(METALNESS) 
TEXTURE_SLOT_ALT(REFLECTION) 
TEXTURE_SLOT_ALT(LUMINANCE_COPY) 
TEXTURE_SLOT_ALT(EMISSIVE) 
TEXTURE_SLOT_ALT(OPACITY) 
TEXTURE_SLOT_ALT(PARTICLES) 
TEXTURE_SLOT_ALT(AO) 
TEXTURE_SLOT_ALT(DEPTH) 
TEXTURE_SLOT_ALT(SHADOWMAP) 
TEXTURE_SLOT_ALT(CUBEMAP) 
TEXTURE_SLOT_ALT(SSAO)
TEXTURE_SLOT_ALT(DUDV)
TEXTURE_SLOT_ALT(SSR)
#endif